version: '3.2'
services:

  jenkinsserver:
    build: ./jenkinsserver
    ports:
      - "80:8080"
#    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - type: volume
        source: jenkinsdata
        target: /var/jenkins_home
        volume:
          nocopy: true
    environment:
      JAVA_OPTS: -Duser.timezone=Europe/Stockholm

  gitserver:
    build: ./gitserver
    restart: always
    container_name: git-server
    ports:
      - "2222:22"
    volumes:
      - type: volume
        source: gitdata
        target: /git-server/repos
        volume:
          nocopy: true
      - type: volume
        source: keys
        target: /git-server/keys
        volume:
          nocopy: true

volumes:
  jenkinsdata:
  gitdata:
  keys:

